#!/usr/bin/env bash
set -euo pipefail

# Submit the definitive AR-768 cascade training job with stronger defaults.

AR_BATCH_SIZE=${AR_BATCH_SIZE:-12}
AR_NUM_WORKERS=${AR_NUM_WORKERS:-8}
AR_PREFETCH_FACTOR=${AR_PREFETCH_FACTOR:-3}
AR_EVAL_EVERY=${AR_EVAL_EVERY:-2}
AR_SKIP_FINAL_TEST_EVAL=${AR_SKIP_FINAL_TEST_EVAL:-1}
AR_MAX_EPOCHS=${AR_MAX_EPOCHS:-40}
AR_PATIENCE=${AR_PATIENCE:-10}
AR_LR=${AR_LR:-1e-4}
AR_CONSTANT_LR=${AR_CONSTANT_LR:-0}
AR_ENABLE_LORA=${AR_ENABLE_LORA:-0}

echo "Submitting definitive AR-768 cascade run with:"
echo "  AR_BATCH_SIZE=${AR_BATCH_SIZE}"
echo "  AR_NUM_WORKERS=${AR_NUM_WORKERS}"
echo "  AR_PREFETCH_FACTOR=${AR_PREFETCH_FACTOR}"
echo "  AR_EVAL_EVERY=${AR_EVAL_EVERY}"
echo "  AR_SKIP_FINAL_TEST_EVAL=${AR_SKIP_FINAL_TEST_EVAL}"
echo "  AR_MAX_EPOCHS=${AR_MAX_EPOCHS}"
echo "  AR_PATIENCE=${AR_PATIENCE}"
echo "  AR_LR=${AR_LR}"
echo "  AR_CONSTANT_LR=${AR_CONSTANT_LR}"
echo "  AR_ENABLE_LORA=${AR_ENABLE_LORA}"

sbatch --export=ALL,AR_BATCH_SIZE=${AR_BATCH_SIZE},AR_NUM_WORKERS=${AR_NUM_WORKERS},AR_PREFETCH_FACTOR=${AR_PREFETCH_FACTOR},AR_EVAL_EVERY=${AR_EVAL_EVERY},AR_SKIP_FINAL_TEST_EVAL=${AR_SKIP_FINAL_TEST_EVAL},AR_MAX_EPOCHS=${AR_MAX_EPOCHS},AR_PATIENCE=${AR_PATIENCE},AR_LR=${AR_LR},AR_CONSTANT_LR=${AR_CONSTANT_LR},AR_ENABLE_LORA=${AR_ENABLE_LORA} \
  scripts/slurm_ar768_definitive.sh